export type Product = {
  id: string;
  sku: string;
  name: string;
  category: string;
  description: string;
  price: number;
  stock: number;
  imageUrl: string;
  slug: string | null;
  shortDescription: string;
  compareAtPrice: number | null;
  weightValue: number | null;
  weightUnit: string;
  piecesMin: number | null;
  piecesMax: number | null;
  isFeatured: boolean;
  isBestSeller: boolean;
  isNew: boolean;
  isPromo: boolean;
  articleId: string | null;
  storageInstructions: string;
  seoTitle: string | null;
  seoDescription: string | null;
  categoryId: string | null;
};
